openapi: 3.0.1
info:
  title: Sample API
  description: API documentation for Sample API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
tags:
  - name: tasks
    description: Operations related to tasks
paths:
  /tasks:
    get:
      summary: Get all tasks
      tags:
        - tasks
      parameters:
        - name: completed
          in: query
          description: Filter tasks by completion status
          required: false
          schema:
            type: boolean
            example: true
        - name: limit
          in: query
          description: Limit the number of tasks returned
          required: false
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      tags:
        - tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
        title:
          type: string
        completed:
          type: boolean
    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: Invalid input data
        details:
          type: array
          items:
            type: string
          example:
            - Title is required
