openapi: 3.0.1
info:
  title: Sample API
  description: API documentation for Sample API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
tags:
  - name: tasks
    description: Operations related to tasks
paths:
  /tasks:
    $ref: paths/tasks.yaml
